# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d4b44658119b45bfdb2194fbe1a82bbfb253f2dbaf5ed3a3c55db5c5f3c5f760089354a3a160fd2ba0587ae2e912b9e9709d6bbb5f5fd41246d94945c1c4be

test:
  secret_key_base: 50f62357db249aa22093cc5b9b46bcdecb07b57f430e980e7eb2cbbf1edaf9f7d1766c32e16c6aaa1e26fe8c757d34c08be709aa786f044ddb0ec8cd362afba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
